#!/usr/bin/env bash
# Bench reproductible GasLib-582 / nomination_mild_618 (Phase I).
# Usage: ./scripts/bench-gaslib-582.sh [tag]   → écrit /tmp/582-<tag>.json
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TAG="${1:-nominal}"
OUT="${GAZFLOW_582_BENCH_OUT:-/tmp/582-${TAG}.json}"

cd "$ROOT/back"
if [[ "${GAZFLOW_582_SKIP_BUILD:-0}" != "1" ]]; then
  cargo build --release --bin compressor_diag
fi

export GAZFLOW_COMPRESSOR_MAP_MODE="${GAZFLOW_COMPRESSOR_MAP_MODE:-measurement}"
export GAZFLOW_CONTRACT_BOUNDARY_REFINEMENT="${GAZFLOW_CONTRACT_BOUNDARY_REFINEMENT:-0}"
export GAZFLOW_NEWTON_COMPRESSOR_HEAD_JAC="${GAZFLOW_NEWTON_COMPRESSOR_HEAD_JAC:-0}"
export GAZFLOW_COMPRESSOR_ENTHALPIC="${GAZFLOW_COMPRESSOR_ENTHALPIC:-0}"
export GAZFLOW_COMPRESSOR_ENERGY_CLOSURE="${GAZFLOW_COMPRESSOR_ENERGY_CLOSURE:-0}"
export GAZFLOW_COMPRESSOR_ENERGY_EQUATION="${GAZFLOW_COMPRESSOR_ENERGY_EQUATION:-0}"
export GAZFLOW_SCENARIO_PRESSURE_CLAMP="${GAZFLOW_SCENARIO_PRESSURE_CLAMP:-0}"
export GAZFLOW_COMPRESSOR_STRICT_NEWTON="${GAZFLOW_COMPRESSOR_STRICT_NEWTON:-0}"
export GAZFLOW_SCENARIO_SHORTPIPE_COUPLED_ENVELOPES="${GAZFLOW_SCENARIO_SHORTPIPE_COUPLED_ENVELOPES:-0}"
export GAZFLOW_SCENARIO_PRESSURE_FLOOR_ANCHOR="${GAZFLOW_SCENARIO_PRESSURE_FLOOR_ANCHOR:-0}"

case "$TAG" in
  strict-newton)
    export GAZFLOW_COMPRESSOR_STRICT_NEWTON=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES="${GAZFLOW_SCENARIO_PRESSURE_ENVELOPES:-0}"
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON="${GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON:-0}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS="${GAZFLOW_TRANSPORT_MINIMAL_ANCHORS:-0}"
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES="${GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES:-4}"
    ;;
  strict-newton-envelopes)
    export GAZFLOW_COMPRESSOR_STRICT_NEWTON=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON=0
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=4
    ;;
  phase-ibis-in-newton)
    export GAZFLOW_COMPRESSOR_STRICT_NEWTON=0
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES="${GAZFLOW_SCENARIO_PRESSURE_ENVELOPES:-1}"
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON="${GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON:-1}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS="${GAZFLOW_TRANSPORT_MINIMAL_ANCHORS:-0}"
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES="${GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES:-4}"
    ;;
  phase-ibis-in-newton-smoke)
    export GAZFLOW_COMPRESSOR_STRICT_NEWTON=0
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ibis-nominal-anchors)
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES="${GAZFLOW_SCENARIO_PRESSURE_ENVELOPES:-1}"
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON="${GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON:-0}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS="${GAZFLOW_TRANSPORT_MINIMAL_ANCHORS:-0}"
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES="${GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES:-4}"
    ;;
  phase-ic-coupled)
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_SCENARIO_SHORTPIPE_COUPLED_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON=0
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=4
    ;;
  phase-ic-floor-anchor)
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_FLOOR_ANCHOR=1
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON=0
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=4
    ;;
  phase-ic-dual-contract)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=4
    ;;
  phase-ic-dual-contract-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ii-enthalpic-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_COMPRESSOR_ENTHALPIC=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ii-direct-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_CONTINUATION_SCALES=1.0
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ii-highstart-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_CONTINUATION_SCALES=0.3,0.6,1.0
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ii-entry-anchor-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ii-entry-anchor)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=4
    ;;
  phase-ii-entry-anchor-80-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR=80
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ii-entry-anchor-enthalpic-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR=70
    export GAZFLOW_COMPRESSOR_ENTHALPIC=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-ibis)
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES="${GAZFLOW_SCENARIO_PRESSURE_ENVELOPES:-1}"
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON="${GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON:-0}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS="${GAZFLOW_TRANSPORT_MINIMAL_ANCHORS:-1}"
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES="${GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES:-0}"
    ;;
  phase-iv-hard-coupling-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_COMPRESSOR_DECISION_VARIABLES=1
    export GAZFLOW_COMPRESSOR_HARD_COUPLING=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-iv-hard-coupling)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_COMPRESSOR_DECISION_VARIABLES=1
    export GAZFLOW_COMPRESSOR_HARD_COUPLING=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=4
    ;;
  phase-vii-cv-setpoint-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_ZERO_FLOW_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_CONTROL_VALVE_AS_REGULATOR=1
    export GAZFLOW_CONTROL_VALVE_DECISION_VARIABLES=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-vii-cv-setpoint-hard-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_ZERO_FLOW_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_COMPRESSOR_DECISION_VARIABLES=1
    export GAZFLOW_COMPRESSOR_HARD_COUPLING=1
    export GAZFLOW_CONTROL_VALVE_AS_REGULATOR=1
    export GAZFLOW_CONTROL_VALVE_DECISION_VARIABLES=1
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-vii-bis-smoke)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_ZERO_FLOW_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_CONTROL_VALVE_AS_REGULATOR=1
    export GAZFLOW_CONTROL_VALVE_DECISION_VARIABLES=1
    export GAZFLOW_CONTROL_VALVE_SOFT_SETPOINT=1
    export GAZFLOW_NOVA_SINK_CAPACITY_STUDY="${GAZFLOW_NOVA_SINK_CAPACITY_STUDY:-0}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  phase-vii-bis-capacity)
    export GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES=1
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR=1
    export GAZFLOW_ENTRY_ZERO_FLOW_ANCHOR=1
    export GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR="${GAZFLOW_ENTRY_TRANSPORT_ANCHOR_BAR:-70}"
    export GAZFLOW_CONTROL_VALVE_AS_REGULATOR=1
    export GAZFLOW_CONTROL_VALVE_DECISION_VARIABLES=1
    export GAZFLOW_CONTROL_VALVE_SOFT_SETPOINT=1
    export GAZFLOW_NOVA_SINK_CAPACITY_STUDY=1
    export GAZFLOW_NOVA_CAPACITY_BISECTION_STEPS="${GAZFLOW_NOVA_CAPACITY_BISECTION_STEPS:-4}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  nominal-smoke)
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES=0
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON=0
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS=0
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES=0
    ;;
  *)
    export GAZFLOW_SCENARIO_PRESSURE_ENVELOPES="${GAZFLOW_SCENARIO_PRESSURE_ENVELOPES:-0}"
    export GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON="${GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON:-0}"
    export GAZFLOW_TRANSPORT_MINIMAL_ANCHORS="${GAZFLOW_TRANSPORT_MINIMAL_ANCHORS:-0}"
    export GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES="${GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES:-4}"
    ;;
esac

echo "bench: tag=$TAG map=$GAZFLOW_COMPRESSOR_MAP_MODE strict=$GAZFLOW_COMPRESSOR_STRICT_NEWTON envelopes=${GAZFLOW_SCENARIO_PRESSURE_ENVELOPES:-0} dual_contract=${GAZFLOW_SCENARIO_BOUNDARY_ACTIVE_ENVELOPES:-0} shortpipe_coupled=$GAZFLOW_SCENARIO_SHORTPIPE_COUPLED_ENVELOPES floor_anchor=$GAZFLOW_SCENARIO_PRESSURE_FLOOR_ANCHOR in_newton=${GAZFLOW_SCENARIO_PRESSURE_IN_NEWTON:-0} clamp=$GAZFLOW_SCENARIO_PRESSURE_CLAMP minimal_anchors=$GAZFLOW_TRANSPORT_MINIMAL_ANCHORS cont_scales=${GAZFLOW_CONTINUATION_SCALES:-default} enthalpic=${GAZFLOW_COMPRESSOR_ENTHALPIC:-0} refine_passes=$GAZFLOW_MASS_BALANCE_REFINEMENT_PASSES"
echo "out: $OUT"

./target/release/compressor_diag GasLib-582 --json "$OUT" || true

python3 - <<PY
import json, sys
d = json.load(open("$OUT"))
mb = d.get("nomination_mass_balance") or d.get("mass_balance") or {}
print("status:", d.get("status"))
print("residual:", d.get("residual"))
print("error:", d.get("error"))
print("nomination_worst:", mb.get("worst_free_node"), mb.get("max_free_imbalance_m3s"))
print("contract_relaxed:", d.get("contract_flow_relaxed"))
flags = d.get("flags") or {}
print("strict:", flags.get("compressor_strict_newton"))
print("envelopes:", flags.get("scenario_pressure_envelopes"))
print("in_newton:", flags.get("scenario_pressure_in_newton"))
pv = mb.get("pressure_violations") or []
print("pressure_violations:", len(pv), pv[:3] if pv else [])
sps = d.get("scenario_pressure_slips") or []
print("scenario_pressure_slips:", len(sps))
for s in sps[:5]:
    print(" ", s["node_id"], "P=", round(s["solved_pressure_bar"],3),
          "shortfall=", round(s["shortfall_bar"],2), "partner=", s.get("shortpipe_partner_id"))
trace = d.get("worst_pressure_upstream_trace") or []
if trace:
    print("upstream_trace:", [(h["node_id"], round(h["pressure_bar"],2)) for h in trace[:8]])
supply = d.get("boundary_pressure_supply") or []
print("pressure_supply:", len(supply))
for s in supply[:5]:
    print(" ", s["node_id"], "need=", s.get("required_lower_bar"),
          "max_up=", round(s["max_upstream_pressure_bar"],2),
          "gap=", round(s["supply_gap_bar"],1))
cap = d.get("sink_capacity_report") or []
if cap:
    print("sink_capacity_report:", len(cap))
    for c in cap:
        print(" ", c["sink_id"],
              "frac=", round(c.get("feasible_fraction", 0), 3),
              "max_q=", round(c.get("max_feasible_q_m3s", 0), 4),
              "nominal=", round(c.get("nominal_q_m3s", 0), 4),
              "shortfall=", round(c.get("pressure_shortfall_bar", 0), 2))
PY
